// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdjRGbm2lrlPF7gGtfYYuCDeJACZH6uk',
    appId: '1:922951008028:web:bba0575118482cace0c4d9',
    messagingSenderId: '922951008028',
    projectId: 'appastra-f2ada',
    authDomain: 'appastra-f2ada.firebaseapp.com',
    storageBucket: 'appastra-f2ada.firebasestorage.app',
    measurementId: 'G-RGB682REXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrg50aBRTHCXB3MY2l3cZeqzpthCCOqQ',
    appId: '1:922951008028:android:bd5566f249067e4ae0c4d9',
    messagingSenderId: '922951008028',
    projectId: 'appastra-f2ada',
    storageBucket: 'appastra-f2ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqxDUpD25NFFF0gfeglBACgZP-r5s-P8',
    appId: '1:922951008028:ios:531e42a942b43b24e0c4d9',
    messagingSenderId: '922951008028',
    projectId: 'appastra-f2ada',
    storageBucket: 'appastra-f2ada.firebasestorage.app',
    androidClientId: '922951008028-2hsn3nhciqcq2bqu8hqueag6mfarfst2.apps.googleusercontent.com',
    iosClientId: '922951008028-r2fkg3m00927g101i4ir3snoj8jeifts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnqxDUpD25NFFF0gfeglBACgZP-r5s-P8',
    appId: '1:922951008028:ios:531e42a942b43b24e0c4d9',
    messagingSenderId: '922951008028',
    projectId: 'appastra-f2ada',
    storageBucket: 'appastra-f2ada.firebasestorage.app',
    androidClientId: '922951008028-2hsn3nhciqcq2bqu8hqueag6mfarfst2.apps.googleusercontent.com',
    iosClientId: '922951008028-r2fkg3m00927g101i4ir3snoj8jeifts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsdjRGbm2lrlPF7gGtfYYuCDeJACZH6uk',
    appId: '1:922951008028:web:f82e193bac2da7e2e0c4d9',
    messagingSenderId: '922951008028',
    projectId: 'appastra-f2ada',
    authDomain: 'appastra-f2ada.firebaseapp.com',
    storageBucket: 'appastra-f2ada.firebasestorage.app',
    measurementId: 'G-XJBD7WHZJM',
  );
}
